### PR TITLE
css-brochure-form exercise - Adrian Arias

### PR DESCRIPTION
**Pull request by adrianm-arias**
Screen Shot 2022-06-29 at 5 39 30 PM

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Getting there. However, there are some areas that need adjusting:
- The label font sizes should be a little smaller, relative to the size of their form controls.
- The labels and placeholders need to be indented from the left side of their form controls more.
- The select element should be the same width as the inputs.
- The submit button needs to be rounded more.

**Comment by adrianm-arias** [comment]
Screen Shot 2022-06-29 at 5 57 09 PM

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Much better! However, please make sure the select element's value is aligned to the left:

---

image

---

image

**Comment by adrianm-arias** [comment]
Screen Shot 2022-06-29 at 6 49 29 PM

**Review by Zhiwutian — APPROVED** [review]
👍🏼

**Pull request merged**
